### ISSUE TITLE
Skipped slides result in misaligned slide/note ouput

### ISSUE THREAD

**Issue by mikepqr** [mcfunley/keynote-fix#3]
Slides and their notes get out of alignment in the HTML output if there are skipped slides in the presentation.

**Comment by mcfunley** [comment]
Derp, would love to take a PR to fix that

**Comment by mcfunley** [comment]
(Inadvertently closed the issue, sorry about that)

**Comment by mikepqr** [comment]
The fix is not obvious to me (never used `appscript`), but I'll take a look.
